# Generated by Django 5.0.6 on 2024-05-20 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 18, 25, 51, 650805, tzinfo=datetime.timezone.utc)),
        ),
    ]
