# Generated by Django 4.2 on 2024-05-18 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 22, 45, 0, 323350, tzinfo=datetime.timezone.utc), verbose_name='Fecha Caducidad'),
        ),
    ]
